name: Job Outputs Example

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.set-output.outputs.msg }}
    steps:
      - id: set-output
        run: echo "msg=Hello from Job 1" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Message from Job 1: ${{ needs.job1.outputs.message }}"
