name: Multiple Runners Example

on:
  push:
    branches:
      - main

jobs:
  linux-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running on Linux"

  windows-job:
    needs: linux-job
    runs-on: windows-latest
    steps:
      - run: echo "Running on Windows"
